FROM fedora:35

# Default Redis Commander port
EXPOSE 8081

RUN yum install -y --setopt=tsflags=nodocs --nogpgcheck npm \
    && npm install -g redis-commander \
    && chown 1001:1001 /usr/local/lib/node_modules/redis-commander/config/ \
    && yum -y clean all --enablerepo='*'

USER 1001

CMD ["redis-commander"]
